# -*- coding: utf-8 -*-

ugm = {"Slovenija": "Ljubljana",
       "Hrvaška": "Zagreb",
       "Avstrija": "Dunaj",
       "Nemčija": "Berlin",
       "Finska": "Helsinki",
       "Irska": "Dublin",
       "Švica": "Bern",
       "Portugalska": "Lizbona",
       "Ukrajina": "Kijev",
       "Španija": "Madrid",
       "Norveška": "Oslo",
       "Italija": "Rim",
       "Bosna in Hercegovina": "Sarajevo",
       "Nizozemska": "Amsterdam",
       "Slovaška": "Bratislava",
       "Belgija": "Bruselj",
       "Madžarska": "Budimpešta",
       "Romunija": "Bukarešta",
       "Belorusija": "Minsk",
       "Makedonija": "Skopje",
       "Srbija": "Beograd",
       "Turčija": "Ankara",
       "Moldavija": "Kišinjev",
       "Švedska": "Stockholm",
       "Andorra": "Andorra la Vella",
       "Grčija": "Atene",
       "Armenija": "Erevan",
       "Danska": "Kobenhavn",
       "Združeno kraljestvo": "London",
       "Luksemburg": "Luxembourg",
       "Monako": "Monako",
       "Rusija": "Moskva",
       "Ciper": "Nikozija",
       "Francija": "Pariz",
       "Črna gora": "Podgorica",
       "Češka": "Praga",
       "Islandija": "Reykjavik",
       "Latvija": "Riga",
       "San Marino": "San Marino",
       "Bolgarija": "Sofia",
       "Estonija": "Talin",
       "Gruzija": "Tbilisi",
       "Albanija": "Tirana",
       "Ferski otoki": "Torshavn",
       "Lihtenštajn": "Vaduz",
       "Malta": "Valletta",
       "Poljska": "Varšava",
       "Vatikan": "Vatikan",
       "Litva": "Vilna",
       }
